name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  build-apk:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          python3 \
          python3-dev \
          python3-pip \
          python3-venv \
          python3-wheel \
          libffi-dev \
          libssl-dev \
          zip \
          unzip \
          openjdk-11-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev \
          ccache
    
    - name: Set up ccache
      run: |
        sudo apt-get install ccache
        echo "/usr/lib/ccache" >> $GITHUB_PATH
    
    - name: Cache buildozer global directory
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: buildozer-${{ hashFiles('buildozer.spec') }}
    
    - name: Cache buildozer directory in project
      uses: actions/cache@v3
      with:
        path: .buildozer
        key: buildozer-${{ hashFiles('buildozer.spec') }}-${{ hashFiles('main.py') }}
    
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip wheel setuptools
        python3 -m pip install buildozer cython
    
    - name: Validate buildozer.spec exists
      run: |
        if [ ! -f buildozer.spec ]; then
          echo "buildozer.spec not found! Creating default..."
          buildozer init
        else
          echo "buildozer.spec found ✓"
        fi
        ls -la
    
    - name: Set environment variables for headless build
      run: |
        echo "DISPLAY=" >> $GITHUB_ENV
        echo "KIVY_WINDOW=none" >> $GITHUB_ENV
        echo "KIVY_GL_BACKEND=gl" >> $GITHUB_ENV
    
    - name: Build APK with Buildozer
      run: |
        # Создаем виртуальный дисплей для headless сборки
        export DISPLAY=:99
        sudo apt-get install -y xvfb
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        
        # Показываем содержимое файлов
        echo "=== Contents of main.py ==="
        head -20 main.py
        echo "=== Contents of buildozer.spec ==="
        head -20 buildozer.spec
        
        # Собираем APK
        buildozer android debug --verbose
      env:
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true"
        JAVA_OPTS: "-Xmx2048m"
    
    - name: List build directory
      run: |
        echo "=== Build directory contents ==="
        ls -la
        if [ -d "bin" ]; then
          echo "=== APK files ==="
          ls -la bin/
          file bin/*.apk 2>/dev/null || echo "No APK files found"
        else
          echo "bin directory not found"
        fi
        
        if [ -d ".buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists" ]; then
          echo "=== Buildozer dists ==="
          find .buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists -name "*.apk" -ls
        fi
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: messenger-apk
        path: |
          bin/*.apk
          .buildozer/android/platform/build-*/dists/*/bin/*.apk
        retention-days: 30
        if-no-files-found: error
    
    - name: Upload build logs on failure
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: build-logs
        path: |
          .buildozer/android/platform/build-*/dists/*/build.log
          .buildozer/logs/
        retention-days: 7
        if-no-files-found: ignore
